/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-05-29 06:19:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.UserBean;
import main.Connexion;
import main.Connexion;
import java.util.ArrayList;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Header_main.jsp", Long.valueOf(1432620853545L));
    _jspx_dependants.put("/Header_connecter.jsp", Long.valueOf(1432620853535L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset= UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--A Design by W3layouts\r\n");
      out.write("Author: W3layout\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Surfhouse Bootstarp Website Template | Checkout ::\r\n");
      out.write("\tw3layouts</title>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"css/component.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!--webfont-->\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<script src=\"js/jquery.easydropdown.js\"></script>\r\n");
      out.write("<!-- Add fancyBox main JS and CSS files -->\r\n");
      out.write("<script src=\"js/jquery.magnific-popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"css/magnific-popup.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script>\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t$('.popup-with-zoom-anim').magnificPopup({\r\n");
      out.write("\t\t\t\t\ttype: 'inline',\r\n");
      out.write("\t\t\t\t\tfixedContentPos: false,\r\n");
      out.write("\t\t\t\t\tfixedBgPos: true,\r\n");
      out.write("\t\t\t\t\toverflowY: 'auto',\r\n");
      out.write("\t\t\t\t\tcloseBtnInside: true,\r\n");
      out.write("\t\t\t\t\tpreloader: false,\r\n");
      out.write("\t\t\t\t\tmidClick: true,\r\n");
      out.write("\t\t\t\t\tremovalDelay: 300,\r\n");
      out.write("\t\t\t\t\tmainClass: 'my-mfp-zoom-in'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<!----details-product-slider--->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
 String user= (String) request.getSession().getAttribute("id"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(user!= null) { 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");

  String nb= Connexion.nbArticle((String)request.getSession().getAttribute("id"));
  String sum=Connexion.sommePanier((String)request.getSession().getAttribute("id"));

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"header-top\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"index.jsp\"><img src=\"images/logo.png\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"header_right\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"> <i class=\"fb\"> </i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><i class=\"tw\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><i class=\"utube\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><i class=\"pin\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><i class=\"instagram\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"lang_list\">\r\n");
      out.write("\t\t\t\t\t\t<select tabindex=\"4\" class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\" class=\"label\" value=\"\">En</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">English</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">French</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">German</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"index-banner\">\r\n");
      out.write("\t\t\t\t<div class=\"wmuSlider example1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wmuSliderWrapper\">\r\n");
      out.write("\t\t\t\t\t\t<article style=\"position: relative; width: 100%; opacity: 1;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"banner-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bannertop_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"login_text\"><a href=\"index.jsp\">");
      out.print(session.getAttribute("id"));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"wish\"><a href=\"Deconnection.jsp\">Log out</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart_bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"cart_icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"cart_desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$");
      out.print(sum);
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"yellow\">");
      out.print(nb);
      out.write(" items</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"product_control_buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/close.png\" alt=\"\" /></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Edit</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"quick_access\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"view_cart\"><a href=\"checkout.jsp\">View Cart</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"check\"><a href=\"paiement.jsp\">Checkout</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"recherche\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" value=\"Search\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Search';}\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"search\"> <input type=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"welcome_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>Welcome to Surfhouse</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telit, sed diam nonummy nibh euism</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner_right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tMutation<br> 2014\r\n");
      out.write("\t\t\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation\r\n");
      out.write("\t\t\t\t\t\t\t\t\tullamcorper suscipit lobortis nisl ut aliquip ex ea commodo.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"banner_btn\">Buy Now</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script src=\"js/jquery.wmuSlider.js\"></script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
 }else{ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\t\r\n");
      out.write("      <div class=\"container\"> \r\n");
      out.write("         <div class=\"header-top\">\r\n");
      out.write("      \t\t <div class=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\"><img src=\"images/logo.png\" alt=\"\"/></a>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t   <div class=\"header_right\">\r\n");
      out.write("\t\t\t <ul class=\"social\">\r\n");
      out.write("\t\t\t\t<li><a href=\"\"> <i class=\"fb\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\"><i class=\"tw\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\"><i class=\"utube\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\"><i class=\"pin\"> </i> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\"><i class=\"instagram\"> </i> </a></li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t    <div class=\"lang_list\">\r\n");
      out.write("\t\t\t  <select tabindex=\"4\" class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<option value=\"\" class=\"label\" value=\"\">En</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">English</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">French</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">German</option>\r\n");
      out.write("\t\t\t  </select>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t </div>  \r\n");
      out.write("\t\t <div class=\"index-banner\">\r\n");
      out.write("       \t   <div class=\"wmuSlider example1\">\r\n");
      out.write("\t\t\t   <div class=\"wmuSliderWrapper\">\r\n");
      out.write("\t\t\t\t   <article style=\"position: relative; width: 100%; opacity: 1;\"> \r\n");
      out.write("\t\t\t\t   \t   <div class=\"banner-wrap\">\r\n");
      out.write("\t\t\t\t   \t      <div class=\"bannertop_box\">\r\n");
      out.write("\t\t\t\t   \t\t \t\t<ul class=\"login\">\r\n");
      out.write("\t\t\t\t   \t\t \t\t\t<li class=\"login_text\"><a href=\"login.jsp\">Log in</a></li>\r\n");
      out.write("\t\t\t\t   \t\t \t\t\t<li class=\"wish\"><a href=\"Deconnection.jsp\">Log out</a></li>\r\n");
      out.write("\t\t\t\t   \t\t \t\t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t   \t\t \t\t</ul>\r\n");
      out.write("\t\t\t\t   \t\t \t\t<div class=\"cart_bg\">\r\n");
      out.write("\t\t\t\t\t   \t\t \t\t<ul class=\"cart\">\r\n");
      out.write("\t\t\t\t\t   \t\t \t\t   <i class=\"cart_icon\"></i><p class=\"cart_desc\">$0.00<br><span class=\"yellow\">0 items</span></p>\r\n");
      out.write("\t\t\t\t\t   \t\t \t\t   <div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t\t   \t\t \t\t</ul>\r\n");
      out.write("\t\t\t\t\t   \t\t \t\t<ul class=\"product_control_buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t  \t      <li><a href=\"#\"><img src=\"images/close.png\" alt=\"\"/></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t      <li><a href=\"#\">Edit</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  \t<ul class=\"quick_access\">\r\n");
      out.write("\t\t\t\t   \t\t \t\t\t<li class=\"view_cart\"><a href=\"login.jsp\">View Cart</a></li>\r\n");
      out.write("\t\t\t\t   \t\t \t\t\t<li class=\"check\"><a href=\"login.jsp\">Checkout</a></li>\r\n");
      out.write("\t\t\t\t   \t\t \t\t\t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t   \t\t \t\t</ul>\r\n");
      out.write("\t\t\t\t   \t\t \t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t   <input type=\"text\" value=\"Search\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Search';}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input type=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  \t\t\t<div class=\"welcome_box\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t<h2>Welcome to Surfhouse</h2>\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euism</p>\r\n");
      out.write("\t\t\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t   \t\t \t</div>\r\n");
      out.write("\t\t\t\t   \t\t \t<div class=\"banner_right\">\r\n");
      out.write("\t\t\t\t   \t\t \t\t<h1>Mutation<br> 2014</h1>\r\n");
      out.write("\t\t\t\t   \t\t \t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo.</p>\r\n");
      out.write("\t\t\t\t   \t\t \t\t<a href=\"#\" class=\"banner_btn\">Buy Now</a>\r\n");
      out.write("\t\t\t\t   \t\t \t</div>\r\n");
      out.write("\t\t\t\t   \t\t \t<div class='clearfix'></div>\r\n");
      out.write("\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t   </article>\r\n");
      out.write("\t\t\t\t </div>          \r\n");
      out.write("            </div>\r\n");
      out.write("            <script src=\"js/jquery.wmuSlider.js\"></script> \t\t   \t           \t      \r\n");
      out.write("      </div>\r\n");
      out.write("\t </div>     \r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
 String item= Connexion.nbArticle((String)request.getSession().getAttribute("id")); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"register\">\r\n");
      out.write("\t\t\t\t");
if(Integer.parseInt(item)==0) { 
      out.write("\r\n");
      out.write("\t\t\t\t<h4 class=\"title\">Shopping cart is empty</h4>\r\n");
      out.write("\t\t\t\t<p class=\"cart\">\r\n");
      out.write("\t\t\t\t\tYou have no items in your shopping cart.<br>Click<a\r\n");
      out.write("\t\t\t\t\t\thref=\"index.jsp\"> here</a> to continue shopping\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t");
} else {
		  		ArrayList <String>articles = Connexion.panierClient(user);
		  		for (String s : articles){ 
      out.write("\r\n");
      out.write("\t\t\t\t <ul class=\"list-inline\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(s);
      out.write("</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"deletePanier\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Clear\" class=\"cbp-vm-icon cbp-vm-add\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"brands\">\r\n");
      out.write("\t\t\t<ul class=\"brand_icons\">\r\n");
      out.write("\t\t\t\t<li><img src='images/icon1.jpg' class=\"img-responsive\" alt=\"\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src='images/icon2.jpg' class=\"img-responsive\" alt=\"\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src='images/icon3.jpg' class=\"img-responsive\" alt=\"\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src='images/icon4.jpg' class=\"img-responsive\" alt=\"\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src='images/icon5.jpg' class=\"img-responsive\" alt=\"\" /></li>\r\n");
      out.write("\t\t\t\t<li><img src='images/icon6.jpg' class=\"img-responsive\" alt=\"\" /></li>\r\n");
      out.write("\t\t\t\t<li class=\"last\"><img src='images/icon7.jpg'\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\" alt=\"\" /></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"instagram_top\">\r\n");
      out.write("\t\t\t<div class=\"instagram text-center\">\r\n");
      out.write("\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t<i class=\"insta_icon\"> </i> Instagram feed:&nbsp;<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"small\">#Surfhouse</span>\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"instagram_grid\">\r\n");
      out.write("\t\t\t\t<li><a class=\"popup-with-zoom-anim\" href=\"#small-dialog1\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/i1.jpg\" class=\"img-responsive\" alt=\"\" /></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"popup-with-zoom-anim\" href=\"#small-dialog1\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/i2.jpg\" class=\"img-responsive\" alt=\"\" /></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"popup-with-zoom-anim\" href=\"#small-dialog1\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/i3.jpg\" class=\"img-responsive\" alt=\"\" /></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"popup-with-zoom-anim\" href=\"#small-dialog1\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/i4.jpg\" class=\"img-responsive\" alt=\"\" /></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"popup-with-zoom-anim\" href=\"#small-dialog1\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/i5.jpg\" class=\"img-responsive\" alt=\"\" /></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"last_instagram\"><a class=\"popup-with-zoom-anim\"\r\n");
      out.write("\t\t\t\t\thref=\"#small-dialog1\"><img src=\"images/i6.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-responsive\" alt=\"\" /></a></li>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"small-dialog1\" class=\"mfp-hide\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pop_up\">\r\n");
      out.write("\t\t\t\t\t\t<h4>A Sample Photo Stream</h4>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/i_zoom.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul class=\"footer_social\">\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fb\"> </i> </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"tw\"> </i> </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"pin\"> </i> </a></li>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"footer-grid\">\r\n");
      out.write("\t\t\t\t<h3>Category</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"list1\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Eshop</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Features</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">New Collections</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-grid\">\r\n");
      out.write("\t\t\t\t<h3>Our Account</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"list1\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Your Account</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Personal information</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Addresses</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Discount</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Orders history</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Addresses</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Search Terms</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-grid\">\r\n");
      out.write("\t\t\t\t<h3>Our Support</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"list1\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Site Map</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Search Terms</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Advanced Search</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Mobile</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Mobile</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Addresses</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-grid\">\r\n");
      out.write("\t\t\t\t<h3>Newsletter</h3>\r\n");
      out.write("\t\t\t\t<p class=\"footer_desc\">Nostrud exerci tation ullamcorper\r\n");
      out.write("\t\t\t\t\tsuscipit lobortis nisl ut aliquip ex ea commodo consequat</p>\r\n");
      out.write("\t\t\t\t<div class=\"search_footer\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"text\" value=\"Insert Email\"\r\n");
      out.write("\t\t\t\t\t\tonfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Insert Email';}\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<img src=\"images/payment.png\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-grid footer-grid_last\">\r\n");
      out.write("\t\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t\t<p class=\"footer_desc\">Diam nonummy nibh euismod tincidunt ut\r\n");
      out.write("\t\t\t\t\tlaoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim\r\n");
      out.write("\t\t\t\t\tveniam,.</p>\r\n");
      out.write("\t\t\t\t<p class=\"f_text\">Phone: &nbsp;&nbsp;&nbsp;00-250-2131</p>\r\n");
      out.write("\t\t\t\t<p class=\"email\">\r\n");
      out.write("\t\t\t\t\tEmail: &nbsp;&nbsp;&nbsp;<span>info(at)Surfhouse.com</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer_bottom\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"copy\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t&copy; 2014 Template by <a href=\"http://w3layouts.com\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_blank\"> w3layouts</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
